import { Center, Flex, useDisclosure } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect, useState } from "react";
import { AppBar } from "../components/AppBar";
import { CardProduct } from "../components/Product/CardProduct";

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [isAdmin, setAdmin] = useState(true);
  const [product, setProduct] = useState(null);
  const [current, setCurrent] = useState("list");
  const [products, setProducts] = useState([]);

  useEffect(() => {
    const getProductsList = async () => {
      const response = await fetch("http://localhost:3001/getProductsList", {
        method: "GET",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
      });

      const result = await response.json();
      setProducts(result);
    };

    getProductsList().catch(console.error);
  }, []);

  useEffect(() => {
    if (!isOpen) setCurrent("list");
  }, [isOpen]);

  return (
    <>
      <Head>
        <title>DHT Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="column">
        <AppBar
          current={current}
          product={product}
          isOpen={isOpen}
          onClose={onClose}
          onOpen={onOpen}
          setCurrent={setCurrent}
        ></AppBar>
        <Center>
          <Flex width="70%" mt={"2rem"} flexWrap="wrap">
            {products.map((product) => {
              const productObject = {
                id: product.id,
                title: product.nome,
                description: product.descricao,
                price: product.preco,
                qty: product.quantidade,
              };
              return (
                <CardProduct
                  isAdmin={isAdmin}
                  key={product.id}
                  id={product.id}
                  product={productObject}
                  setCurrent={setCurrent}
                  setProduct={setProduct}
                  onOpen={onOpen}
                />
              );
            })}
          </Flex>
        </Center>
      </Flex>
    </>
  );
}
